[pytest]
testpaths = tests
python_files = test_*.py
norecursedirs =
    .git
    .pytest_cache
    __pycache__
    kaggle_kernel/new_kernel/kernel_logs
    kaggle_kernel/new_kernel/kernel_out
    kaggle_kernel/new_kernel/uncensor
    uncensor
